version : "3.9"
services:
  zookeeper:
    image: zookeeper  
    container_name: zookeeper
    volumes:
      - ./zookeeper:/data
  
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - ./kafka:/bitnami/kafka/data
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED.LISTENER=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    # kafka ต้องใช้ zookeeper ต้องให้ zookeeper start ขึ้นมาก่อน
      - zookeeper
